print("my name is Marvan Verma")
print("my age is 9")
print("my favorite color is blue")
print("my favorite food is pizza")
print("my favorite animal is a dog")
print("my favorite sport is soccer")
print("i study at Stamford American International School")
print("my favorite subject is science")
print("my favorite hobby is coding")
print("my favorite movie is The Lion King")
print("my favorite book is Harry Potter")
print("my favorite music genre is pop")
print("my favorite singer is Bruno Mars")
print("my favorite band is Maroon 5")
